import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Claim } from './apiClient';

interface ReportOptions {
  claim: Claim;
  farmerName: string;
  farmerEmail: string;
  farmName: string;
  farmDistrict: string;
  farmVillage: string;
  farmLatitude?: number;
  farmLongitude?: number;
  cropType: string;
}

// ─── Constants ────────────────────────────────────────────────────────────────
const BRAND_GREEN  = [22, 163, 74]  as [number, number, number];
const BRAND_ORANGE = [234, 88, 12]  as [number, number, number];
const BRAND_BLUE   = [37, 99, 235]  as [number, number, number];
const SLATE_900    = [15, 23, 42]   as [number, number, number];
const SLATE_600    = [71, 85, 105]  as [number, number, number];
const SLATE_100    = [241, 245, 249] as [number, number, number];
const AMBER        = [217, 119, 6]  as [number, number, number];
const WHITE        = [255, 255, 255] as [number, number, number];
const PAGE_W = 210;
const PAGE_H = 297;
const ML = 18; // margin left
const MR = 18; // margin right
const CW = PAGE_W - ML - MR; // content width

// ─── Helpers ──────────────────────────────────────────────────────────────────
function setFont(doc: jsPDF, size: number, style: 'normal' | 'bold' = 'normal', color: [number,number,number] = SLATE_900) {
  doc.setFont('helvetica', style);
  doc.setFontSize(size);
  doc.setTextColor(...color);
}

function pageHeader(doc: jsPDF, pageNum: number, totalPages: number) {
  // Top bar
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, PAGE_W, 12, 'F');
  setFont(doc, 8, 'bold', WHITE);
  doc.text('FASALSETU.AI — CROP INSURANCE CLAIM REPORT', ML, 8);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MR, 8, { align: 'right' });

  // Bottom bar
  doc.setFillColor(...SLATE_100);
  doc.rect(0, PAGE_H - 10, PAGE_W, 10, 'F');
  setFont(doc, 7, 'normal', SLATE_600);
  doc.text('This report is auto-generated by FasalSetu.Ai | Powered by NASA POWER & ML Engine', PAGE_W / 2, PAGE_H - 4, { align: 'center' });
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  setFont(doc, 11, 'bold', SLATE_900);
  doc.text(text, ML, y);
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.6);
  doc.line(ML, y + 2, ML + CW, y + 2);
  return y + 10;
}

function highlightBox(
  doc: jsPDF,
  x: number, y: number, w: number, h: number,
  label: string, value: string,
  bg: [number,number,number], textColor: [number,number,number] = WHITE
) {
  doc.setFillColor(...bg);
  doc.roundedRect(x, y, w, h, 3, 3, 'F');
  setFont(doc, 7, 'bold', textColor);
  doc.setTextColor(textColor[0], textColor[1], textColor[2], 0.7);
  doc.text(label.toUpperCase(), x + w / 2, y + 7, { align: 'center' });
  setFont(doc, 16, 'bold', textColor);
  doc.text(value, x + w / 2, y + 18, { align: 'center' });
}

function kv(doc: jsPDF, label: string, value: string, x: number, y: number, labelW = 48): number {
  setFont(doc, 9, 'bold', SLATE_600);
  doc.text(label, x, y);
  setFont(doc, 9, 'normal', SLATE_900);
  doc.text(value || '—', x + labelW, y);
  return y + 7;
}

// ─── Main Generator ───────────────────────────────────────────────────────────
export function generateClaimReport(opts: ReportOptions) {
  const { claim, farmerName, farmerEmail, farmName, farmDistrict, farmVillage, cropType, farmLatitude, farmLongitude } = opts;

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const TOTAL_PAGES = 5;

  const prediction    = claim.prediction || claim.calamityType || 'UNKNOWN';
  const confidence    = claim.aiConfidence ?? 0;
  const confidencePct = Math.round(confidence * 100);
  const damagePercent = claim.damagePercent ?? claim.aiDamageScore ?? 0;
  const estimatedClaim = claim.estimatedClaim ?? claim.estimatedPayout ?? 0;
  const policySummary = claim.policySummary || { 
    sumInsured: claim.totalSumInsured || 0, 
    coverageUsed: claim.coverageApplied || 0 
  };
  const features: Record<string, number> = (claim as any).features || {};
  const claimDate     = claim.dateOfLoss || new Date().toISOString().split('T')[0];
  const claimId       = claim.id ? `CLM-${String(claim.id).padStart(6, '0')}` : 'CLM-PENDING';
  const isLowConf     = confidence < 0.5;
  const predColor     = prediction === 'DROUGHT' ? BRAND_ORANGE : prediction === 'FLOOD' ? BRAND_BLUE : BRAND_GREEN;

  // ─── PAGE 1: CLAIM SUMMARY ──────────────────────────────────────────────────
  pageHeader(doc, 1, TOTAL_PAGES);

  // Main title
  setFont(doc, 20, 'bold', SLATE_900);
  doc.text('Crop Insurance Claim Report', PAGE_W / 2, 30, { align: 'center' });
  setFont(doc, 9, 'normal', SLATE_600);
  doc.text('Official AI-Verified Analysis Document', PAGE_W / 2, 37, { align: 'center' });

  // Divider
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.8);
  doc.line(ML, 41, PAGE_W - MR, 41);

  // Basic info table
  let y = 50;
  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: MR },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: 'bold', textColor: SLATE_600, cellWidth: 48 }, 1: { textColor: SLATE_900 } },
    body: [
      ['Farmer Name',  farmerName],
      ['Claim ID',     claimId],
      ['District',     farmDistrict],
      ['Crop Type',    cropType],
      ['Date of Loss', claimDate],
      ['Farm Name',    farmName],
      ['Village',      farmVillage],
    ],
  });

  // Highlight boxes
  y = (doc as any).lastAutoTable.finalY + 12;
  const bw = (CW - 9) / 4;

  highlightBox(doc, ML,              y, bw, 28, 'Prediction', prediction, predColor);
  highlightBox(doc, ML + bw + 3,     y, bw, 28, 'Confidence', `${confidencePct}%`,
    isLowConf ? AMBER : BRAND_GREEN);
  highlightBox(doc, ML + (bw + 3)*2, y, bw, 28, 'Est. Damage', `${damagePercent.toFixed(2)}%`, SLATE_900);
  highlightBox(doc, ML + (bw + 3)*3, y, bw, 28, 'Est. Claim', `Rs.${estimatedClaim.toLocaleString('en-IN')}`, BRAND_GREEN);

  // Low confidence warning
  if (isLowConf) {
    y += 36;
    doc.setFillColor(255, 251, 235);
    doc.setDrawColor(...AMBER);
    doc.setLineWidth(0.5);
    doc.roundedRect(ML, y, CW, 14, 2, 2, 'FD');
    setFont(doc, 9, 'bold', AMBER);
    doc.text('⚠  LOW CONFIDENCE — MANUAL REVIEW REQUIRED', ML + 5, y + 9);
  }

  // Zero damage note
  if (estimatedClaim === 0) {
    y += isLowConf ? 20 : 36;
    doc.setFillColor(240, 253, 244);
    doc.setDrawColor(...BRAND_GREEN);
    doc.roundedRect(ML, y, CW, 14, 2, 2, 'FD');
    setFont(doc, 9, 'normal', BRAND_GREEN);
    doc.text('No significant crop damage detected by AI engine.', ML + 5, y + 9);
  }

  // ─── PAGE 2: FARMER & POLICY DETAILS ────────────────────────────────────────
  doc.addPage();
  pageHeader(doc, 2, TOTAL_PAGES);

  y = 22;
  y = sectionTitle(doc, '1. Farmer Information', y);

  y = kv(doc, 'Full Name:',   farmerName,   ML, y);
  y = kv(doc, 'Email:',       farmerEmail,  ML, y);
  y = kv(doc, 'Farmer ID:',   `#${claim.farmerId || '—'}`, ML, y);
  y += 6;

  y = sectionTitle(doc, '2. Farm Information', y);

  const col2X = ML + CW / 2;
  const savedY = y;

  // Left column
  kv(doc, 'Farm Name:',  farmName,     ML, y);
  kv(doc, 'Village:',    farmVillage,  ML, y + 7);
  kv(doc, 'District:',   farmDistrict, ML, y + 14);
  // Right column
  kv(doc, 'Latitude:',  farmLatitude  ? farmLatitude.toFixed(4)  : 'N/A', col2X, savedY);
  kv(doc, 'Longitude:', farmLongitude ? farmLongitude.toFixed(4) : 'N/A', col2X, savedY + 7);
  kv(doc, 'Area:',      claim.farmAreaSnapshot ? `${claim.farmAreaSnapshot} Acres` : 'N/A', col2X, savedY + 14);

  y += 30;
  y = sectionTitle(doc, '3. Policy Information', y);

  const sumInsured    = policySummary.sumInsured;
  const coverageUsed  = policySummary.coverageUsed;
  const maxClaim      = sumInsured * coverageUsed;

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: MR },
    theme: 'striped',
    headStyles: { fillColor: BRAND_GREEN, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: SLATE_900 },
    head: [['Parameter', 'Value']],
    body: [
      ['Sum Insured (Total)',      `Rs.${sumInsured.toLocaleString('en-IN')}`],
      ['Coverage Factor',         `${Math.round(coverageUsed * 100)}%`],
      ['Maximum Claimable Amount',`Rs.${maxClaim.toLocaleString('en-IN')}`],
      ['Calamity Type Covered',   claim.calamityType || prediction],
      ['Claim Status',            claim.status || 'MANUAL_REVIEW'],
    ],
  });

  // ─── PAGE 3: AI ANALYSIS REPORT ─────────────────────────────────────────────
  doc.addPage();
  pageHeader(doc, 3, TOTAL_PAGES);

  y = 22;
  setFont(doc, 16, 'bold', SLATE_900);
  doc.text('AI Analysis & Reasoning', ML, y);
  y += 10;

  // Prediction explanation
  y = sectionTitle(doc, 'Prediction Explanation', y);
  setFont(doc, 9, 'normal', SLATE_900);
  const predText = prediction === 'DROUGHT'
    ? 'The AI engine detected drought conditions based on critically low rainfall in the 7-day window and a high historical drought vulnerability score for this district.'
    : prediction === 'FLOOD'
    ? 'The AI engine detected flood conditions based on elevated 7-day cumulative rainfall and a high historical flood risk score for this district.'
    : 'No significant calamity detected. Weather conditions are within normal parameters for this region.';
  const predLines = doc.splitTextToSize(predText, CW);
  doc.text(predLines, ML, y);
  y += predLines.length * 5.5 + 6;

  // Confidence explanation
  y = sectionTitle(doc, 'Confidence Score Explanation', y);
  const confText = isLowConf
    ? `The model returned a confidence of ${confidencePct}% (below 50%). This indicates conflicting signals between the current weather data and historical risk records. A human agent should manually verify this claim before approval.`
    : `The model returned a confidence of ${confidencePct}% (above 50%). Current weather trends strongly align with historical vulnerability patterns for this district, supporting the AI prediction.`;
  const confLines = doc.splitTextToSize(confText, CW);
  setFont(doc, 9, 'normal', SLATE_900);
  doc.text(confLines, ML, y);
  y += confLines.length * 5.5 + 6;

  // Feature Values
  y = sectionTitle(doc, 'Feature Values Used by ML Model', y);
  const histDrought  = features['historical_drought']  ?? (claim.droughtRisk  || 0);
  const histFlood    = features['historical_flood']    ?? (claim.floodRisk    || 0);
  const rainfallCurr = features['rainfall_current']   ?? (claim.rainfallMm   || 0);
  const rainfall7d   = features['rainfall_7d']        ?? (claim.rainfall7d   || 0);

  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: MR },
    theme: 'grid',
    headStyles: { fillColor: SLATE_900, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: { 2: { fontStyle: 'bold' } },
    head: [['Feature', 'Value', 'Interpretation']],
    body: [
      ['Historical Drought Risk',  histDrought.toFixed(4),   histDrought > 0.5 ? 'HIGH RISK' : 'LOW RISK'],
      ['Historical Flood Risk',    histFlood.toFixed(4),     histFlood   > 0.5 ? 'HIGH RISK' : 'LOW RISK'],
      ['Rainfall (Current, mm)',   rainfallCurr.toFixed(2),  rainfallCurr < 1  ? 'Very Low'  : rainfallCurr > 50 ? 'Very High' : 'Moderate'],
      ['Rainfall (7-Day, mm)',     rainfall7d.toFixed(2),    rainfall7d  < 5   ? 'Drought Indicator' : rainfall7d > 100 ? 'Flood Indicator' : 'Normal'],
      ['AI Confidence',            `${confidencePct}%`,      isLowConf ? 'LOW — Manual Review' : 'HIGH — AI Verified'],
    ],
  });

  // Auto-generated reasoning text
  y = (doc as any).lastAutoTable.finalY + 10;
  y = sectionTitle(doc, 'AI-Generated Reasoning', y);
  const reasoning = (() => {
    const raw = claim.explanation || claim.aiReasoning || '';
    const clean = raw.replace(/^null\s*/i, '').trim();
    return clean || (
      prediction === 'DROUGHT'
        ? `Low rainfall (${rainfallCurr.toFixed(1)}mm current, ${rainfall7d.toFixed(1)}mm over 7 days) combined with a high historical drought vulnerability score of ${(histDrought * 100).toFixed(1)}% strongly indicates drought conditions in this region.`
        : `Elevated 7-day rainfall of ${rainfall7d.toFixed(1)}mm combined with a high historical flood risk of ${(histFlood * 100).toFixed(1)}% indicates flood conditions in this region.`
    );
  })();
  const rLines = doc.splitTextToSize(`"${reasoning}"`, CW);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(ML, y - 2, CW, rLines.length * 5.5 + 8, 2, 2, 'F');
  setFont(doc, 9, 'normal', SLATE_600);
  doc.text(rLines, ML + 4, y + 4);

  // ─── PAGE 4: DAMAGE & CLAIM CALCULATION ─────────────────────────────────────
  doc.addPage();
  pageHeader(doc, 4, TOTAL_PAGES);

  y = 22;
  setFont(doc, 16, 'bold', SLATE_900);
  doc.text('Damage & Claim Calculation', ML, y);
  y += 12;

  y = sectionTitle(doc, 'Damage Assessment', y);

  // Large damage % box
  doc.setFillColor(...SLATE_100);
  doc.roundedRect(ML, y, CW, 28, 4, 4, 'F');
  setFont(doc, 10, 'bold', SLATE_600);
  doc.text('ESTIMATED DAMAGE', PAGE_W / 2, y + 9, { align: 'center' });
  setFont(doc, 28, 'bold', predColor);
  doc.text(`${damagePercent.toFixed(2)}%`, PAGE_W / 2, y + 23, { align: 'center' });
  y += 36;

  y = sectionTitle(doc, 'Claim Calculation Formula', y);

  // Formula block
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.4);
  doc.roundedRect(ML, y, CW, 52, 3, 3, 'FD');

  setFont(doc, 10, 'bold', SLATE_900);
  doc.text('Claim  =  Sum Insured  ×  Damage %  ×  Coverage Factor', PAGE_W / 2, y + 12, { align: 'center' });

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(ML + 10, y + 16, ML + CW - 10, y + 16);

  setFont(doc, 10, 'normal', SLATE_600);
  doc.text(`= Rs.${sumInsured.toLocaleString('en-IN')}  ×  ${(damagePercent / 100).toFixed(4)}  ×  ${coverageUsed.toFixed(2)}`, PAGE_W / 2, y + 26, { align: 'center' });

  doc.setDrawColor(...BRAND_GREEN);
  doc.setLineWidth(0.5);
  doc.line(ML + 20, y + 30, ML + CW - 20, y + 30);

  setFont(doc, 18, 'bold', BRAND_GREEN);
  doc.text(`= Rs.${estimatedClaim.toLocaleString('en-IN')}`, PAGE_W / 2, y + 44, { align: 'center' });
  y += 62;

  // Breakdown table
  autoTable(doc, {
    startY: y,
    margin: { left: ML, right: MR },
    theme: 'striped',
    headStyles: { fillColor: BRAND_GREEN, textColor: WHITE, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    head: [['Component', 'Value', 'Note']],
    body: [
      ['Sum Insured',       `Rs.${sumInsured.toLocaleString('en-IN')}`, 'From uploaded policy document'],
      ['Damage Percentage', `${damagePercent.toFixed(2)}%`,             `Based on ${prediction} risk score`],
      ['Coverage Factor',   `${Math.round(coverageUsed * 100)}%`,       'Policy coverage applied'],
      ['Estimated Claim',   `Rs.${estimatedClaim.toLocaleString('en-IN')}`, 'Subject to agent verification'],
    ],
  });

  if (estimatedClaim === 0) {
    y = (doc as any).lastAutoTable.finalY + 8;
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(ML, y, CW, 12, 2, 2, 'F');
    setFont(doc, 9, 'normal', BRAND_GREEN);
    doc.text('No significant damage detected — claim payout is Rs.0.', PAGE_W / 2, y + 8, { align: 'center' });
  }

  // ─── PAGE 5: TIMELINE & DECLARATION ─────────────────────────────────────────
  doc.addPage();
  pageHeader(doc, 5, TOTAL_PAGES);

  y = 22;
  setFont(doc, 16, 'bold', SLATE_900);
  doc.text('Claim Timeline & Declaration', ML, y);
  y += 12;

  y = sectionTitle(doc, 'Process Timeline', y);

  // ── Dynamic timeline driven by claim.status ─────────────────────────────
  const claimStatus  = claim.status || 'PENDING';
  const tlApproved   = claimStatus === 'APPROVED';
  const tlRejected   = claimStatus === 'REJECTED';
  const tlInReview   = claimStatus === 'IN_REVIEW' || claimStatus === 'MANUAL_REVIEW';
  const tlHasAI      = !!(claim.prediction || claim.damagePercent || claim.aiDamageScore);
  const tlHasDamage  = (claim.damagePercent ?? claim.aiDamageScore) != null;
  const tlHasClaim   = (claim.estimatedClaim ?? claim.estimatedPayout) != null;

  const timelineSteps: { label: string; done: boolean; current: boolean; tag: string; tagColor: [number,number,number] }[] = [
    {
      label:    'Claim Submitted',
      done:     true,
      current:  false,
      tag:      'COMPLETED',
      tagColor: BRAND_GREEN,
    },
    {
      label:    'AI Analysis Completed',
      done:     tlHasAI,
      current:  !tlHasAI,
      tag:      tlHasAI ? 'COMPLETED' : 'IN PROGRESS',
      tagColor: tlHasAI ? BRAND_GREEN : BRAND_BLUE,
    },
    {
      label:    'Damage Assessed',
      done:     tlHasDamage,
      current:  tlHasAI && !tlHasDamage,
      tag:      tlHasDamage ? 'COMPLETED' : (tlHasAI ? 'IN PROGRESS' : 'PENDING'),
      tagColor: tlHasDamage ? BRAND_GREEN : (tlHasAI ? BRAND_BLUE : [150, 150, 150] as [number,number,number]),
    },
    {
      label:    'Claim Estimated',
      done:     tlHasClaim,
      current:  tlHasDamage && !tlHasClaim,
      tag:      tlHasClaim ? 'COMPLETED' : (tlHasDamage ? 'IN PROGRESS' : 'PENDING'),
      tagColor: tlHasClaim ? BRAND_GREEN : (tlHasDamage ? BRAND_BLUE : [150, 150, 150] as [number,number,number]),
    },
    {
      label:    tlRejected ? 'Claim Rejected' : tlApproved ? 'Claim Approved' : 'Agent Review',
      done:     tlApproved || tlRejected,
      current:  tlInReview && tlHasClaim,
      tag:      tlRejected ? 'REJECTED' : tlApproved ? 'COMPLETED' : (tlInReview ? 'IN PROGRESS' : 'PENDING'),
      tagColor: tlRejected ? [220, 38, 38] as [number,number,number] : tlApproved ? BRAND_GREEN : (tlInReview ? BRAND_BLUE : [150, 150, 150] as [number,number,number]),
    },
    {
      label:    tlApproved ? 'Payout Processed' : 'Approval Pending',
      done:     tlApproved,
      current:  false,
      tag:      tlApproved ? 'COMPLETED' : 'PENDING',
      tagColor: tlApproved ? BRAND_GREEN : [150, 150, 150] as [number,number,number],
    },
  ];

  timelineSteps.forEach((step, i) => {
    const circleX = ML + 6;
    const stepY   = y + i * 14;
    const fillCol: [number,number,number] = step.done
      ? (step.label.includes('Rejected') ? [220, 38, 38] : BRAND_GREEN)
      : step.current ? BRAND_BLUE
      : [200, 200, 200];

    // Connector line
    if (i < timelineSteps.length - 1) {
      doc.setDrawColor(step.done ? fillCol[0] : 200, step.done ? fillCol[1] : 200, step.done ? fillCol[2] : 200);
      doc.setLineWidth(0.6);
      doc.line(circleX, stepY + 5, circleX, stepY + 13);
    }

    // Circle
    doc.setFillColor(...fillCol);
    doc.circle(circleX, stepY + 1.5, 3, 'F');

    // Checkmark / dot
    setFont(doc, 7, 'bold', WHITE);
    doc.text(step.done ? '\u2713' : (step.current ? '○' : '•'), circleX, stepY + 3.5, { align: 'center' });

    // Label
    setFont(doc, 10, step.done || step.current ? 'bold' : 'normal',
      step.done ? SLATE_900 : step.current ? SLATE_900 : SLATE_600);
    doc.text(step.label, circleX + 8, stepY + 3.5);

    // Status tag (right-aligned)
    setFont(doc, 7, 'bold', step.tagColor);
    doc.text(step.tag, PAGE_W - MR, stepY + 3.5, { align: 'right' });
  });

  y += timelineSteps.length * 14 + 12;

  // Declaration box
  y = sectionTitle(doc, 'Declaration', y);
  const decl = 'This report has been automatically generated by the FasalSetu.Ai platform using real-time NASA POWER satellite weather data, historical district risk datasets, and a Random Forest machine learning model. The AI-estimated damage and claim values are preliminary and subject to final verification and approval by an authorized insurance agent.';
  const declLines = doc.splitTextToSize(decl, CW);
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(...SLATE_600);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, y - 2, CW, declLines.length * 5.5 + 10, 2, 2, 'FD');
  setFont(doc, 8.5, 'normal', SLATE_600);
  doc.text(declLines, ML + 4, y + 5);

  y += declLines.length * 5.5 + 18;

  // Signature area
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.4);
  const sigW = (CW - 10) / 2;
  doc.line(ML, y, ML + sigW, y);
  doc.line(ML + sigW + 10, y, ML + CW, y);
  setFont(doc, 8, 'normal', SLATE_600);
  doc.text('Farmer Signature', ML + sigW / 2, y + 5, { align: 'center' });
  doc.text('Agent / Authorized Signatory', ML + sigW + 10 + sigW / 2, y + 5, { align: 'center' });

  // Generated timestamp
  y += 16;
  setFont(doc, 7, 'normal', SLATE_600);
  doc.text(`Report generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST`, PAGE_W / 2, y, { align: 'center' });
  doc.text(`Claim ID: ${claimId}  |  FasalSetu.Ai Platform`, PAGE_W / 2, y + 5, { align: 'center' });

  // ─── Save ────────────────────────────────────────────────────────────────────
  doc.save(`FasalSetu_ClaimReport_${claimId}_${claimDate}.pdf`);
}
