import os
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from io import BytesIO

class ReportGenerator:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_charts(self, confidence, features):
        """Generates charts for the PDF and returns them as BytesIO objects."""
        # 1. Pie Chart (Damage vs Normal)
        pie_io = BytesIO()
        plt.figure(figsize=(4, 4))
        labels = ['Damage Prob', 'Normal Prob']
        sizes = [confidence * 100, (1 - confidence) * 100]
        colors = ['#ef4444', '#10b981']
        plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors)
        plt.axis('equal')
        plt.savefig(pie_io, format='png', transparent=True)
        plt.close()
        pie_io.seek(0)

        # 2. Bar Chart (Features)
        bar_io = BytesIO()
        plt.figure(figsize=(6, 4))
        f_names = ['NDVI Δ', 'Rainfall', 'SAR Δ']
        f_values = [
            abs(features.get('delta_ndvi', 0)),
            features.get('rainfall', 0) / 100, # Normalized for chart
            abs(features.get('delta_sar', 0))
        ]
        plt.bar(f_names, f_values, color=['#3b82f6', '#6366f1', '#8b5cf6'])
        plt.title("Satellite & Weather Signals")
        plt.ylabel("Normalized Intensity")
        plt.savefig(bar_io, format='png', transparent=True)
        plt.close()
        bar_io.seek(0)

        return pie_io, bar_io

    def create_pdf(self, claim_id, data):
        """Generates a professional PDF report."""
        file_path = os.path.join(self.output_dir, f"claim_{claim_id}.pdf")
        c = canvas.Canvas(file_path, pagesize=letter)
        width, height = letter

        # Header
        c.setFont("Helvetica-Bold", 24)
        c.setFillColorRGB(0.06, 0.45, 0.32) # Brand Green
        c.drawString(50, height - 50, "FasalSetu.Ai Assessment Report")
        
        c.setFont("Helvetica", 12)
        c.setFillColorRGB(0.4, 0.4, 0.4)
        c.drawString(50, height - 70, f"Claim ID: #{claim_id} | Date: {data.get('date', 'N/A')}")
        
        c.setStrokeColorRGB(0.9, 0.9, 0.9)
        c.line(50, height - 85, width - 50, height - 85)

        # Farmer Details
        c.setFont("Helvetica-Bold", 14)
        c.setFillColorRGB(0.1, 0.1, 0.1)
        c.drawString(50, height - 110, "Farmer Information")
        c.setFont("Helvetica", 11)
        c.drawString(50, height - 130, f"Farmer Name: {data.get('farmer_name', 'Verified Farmer')}")
        c.drawString(50, height - 145, f"Location: {data.get('lat', 0)}, {data.get('lon', 0)}")
        c.drawString(50, height - 160, f"District: {data.get('district', 'N/A')}")

        # Prediction Result
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 190, "AI Decision Summary")
        c.setFont("Helvetica-Bold", 18)
        c.setFillColorRGB(0.8, 0.1, 0.1) if "FLOOD" in data.get('prediction', '') else c.setFillColorRGB(0.1, 0.6, 0.1)
        c.drawString(50, height - 215, data.get('prediction', 'PENDING'))
        
        c.setFont("Helvetica", 11)
        c.setFillColorRGB(0.3, 0.3, 0.3)
        c.drawString(50, height - 230, f"System Confidence: {round(data.get('confidence', 0) * 100, 2)}%")

        # Charts
        pie_io, bar_io = self.generate_charts(data.get('confidence', 0), data.get('features', {}))
        
        c.drawImage(ImageReader(pie_io), 300, height - 260, width=180, height=180)
        c.drawImage(ImageReader(bar_io), 50, height - 480, width=350, height=200)

        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColorRGB(0.6, 0.6, 0.6)
        c.drawString(50, 40, "This report is generated by FasalSetu AI Engine. Final payout is subject to human agent review.")

        c.showPage()
        c.save()
        return file_path

report_gen = ReportGenerator()
